kind: Service
apiVersion: v1
metadata:
  name: nsdb
spec:
  type: NodePort
  selector:
    app: nsdb
  ports:
  - protocol: TCP
    name: management
    port: 8558
    targetPort: management
  - protocol: TCP
    name: http
    port: 9000
    targetPort: http
  - protocol: TCP
    name: grpc
    port: 7817
    targetPort: grpc