addSbtPlugin("com.geirsson"                      % "sbt-scalafmt"        % "0.6.3")
addSbtPlugin("org.scoverage"                     % "sbt-scoverage"       % "1.5.0")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings"    % "latest.release")
addSbtPlugin("de.heikoseeberger"                 % "sbt-header"          % "2.0.0")
addSbtPlugin("com.typesafe.sbt"                  % "sbt-multi-jvm"       % "0.4.0")
addSbtPlugin("io.gatling"                        % "gatling-sbt"         % "2.2.0")
addSbtPlugin("com.typesafe.sbt"                  % "sbt-native-packager" % "1.3.2")
addSbtPlugin("com.eltimn"                        % "sbt-frontend"        % "0.3.0")
