/**
 * normal types
 */

const TAB_ADD = '@@nsdb/TAB_ADD';
const TAB_REMOVE = '@@nsdb/TAB_REMOVE';
const NAMESPACE_SELECT = '@@nsdb/NAMESPACE_SELECT';
const METRIC_SELECT = '@@nsdb/METRIC_SELECT';

/**
 * async types
 */

const NAMESPACES_FETCH_REQUEST = '@@nsdb/NAMESPACES_FETCH_REQUEST';
const NAMESPACES_FETCH_SUCCESS = '@@nsdb/NAMESPACES_FETCH_SUCCESS';
const NAMESPACES_FETCH_ERROR = '@@nsdb/NAMESPACES_FETCH_ERROR';

const METRICS_FETCH_REQUEST = '@@nsdb/METRICS_FETCH_REQUEST';
const METRICS_FETCH_SUCCESS = '@@nsdb/METRICS_FETCH_SUCCESS';
const METRICS_FETCH_ERROR = '@@nsdb/METRICS_FETCH_ERROR';

const METRIC_DESCRIPTION_FETCH_REQUEST = '@@nsdb/METRIC_DESCRIPTION_FETCH_REQUEST';
const METRIC_DESCRIPTION_FETCH_SUCCESS = '@@nsdb/METRIC_DESCRIPTION_FETCH_SUCCESS';
const METRIC_DESCRIPTION_FETCH_ERROR = '@@nsdb/METRIC_DESCRIPTION_FETCH_ERROR';

const HISTORICAL_QUERY_FETCH_REQUEST = '@@nsdb/HISTORICAL_QUERY_FETCH_REQUEST';
const HISTORICAL_QUERY_FETCH_SUCCESS = '@@nsdb/HISTORICAL_QUERY_FETCH_SUCCESS';
const HISTORICAL_QUERY_FETCH_ERROR = '@@nsdb/HISTORICAL_QUERY_FETCH_ERROR';

const REALTIME_QUERY_START = '@@nsdb/REALTIME_QUERY_START';
const REALTIME_QUERY_STOP = '@@nsdb/REALTIME_QUERY_STOP';
const REALTIME_QUERY_MESSAGE = '@@nsdb/REALTIME_QUERY_MESSAGE';
const REALTIME_QUERY_ERROR = '@@nsdb/REALTIME_QUERY_ERROR';

export const types = {
  TAB_ADD,
  TAB_REMOVE,
  NAMESPACE_SELECT,
  METRIC_SELECT,
  NAMESPACES_FETCH_REQUEST,
  NAMESPACES_FETCH_SUCCESS,
  NAMESPACES_FETCH_ERROR,
  METRICS_FETCH_REQUEST,
  METRICS_FETCH_SUCCESS,
  METRICS_FETCH_ERROR,
  METRIC_DESCRIPTION_FETCH_REQUEST,
  METRIC_DESCRIPTION_FETCH_SUCCESS,
  METRIC_DESCRIPTION_FETCH_ERROR,
  HISTORICAL_QUERY_FETCH_REQUEST,
  HISTORICAL_QUERY_FETCH_SUCCESS,
  HISTORICAL_QUERY_FETCH_ERROR,
  REALTIME_QUERY_START,
  REALTIME_QUERY_STOP,
  REALTIME_QUERY_MESSAGE,
  REALTIME_QUERY_ERROR,
};
