/**
 * normal types
 */

const RESULT_REMOVE = '@@nsdb/RESULT_REMOVE';

/**
 * async types
 */

const HISTORICAL_QUERY_FETCH_REQUEST = '@@nsdb/HISTORICAL_QUERY_FETCH_REQUEST';
const HISTORICAL_QUERY_FETCH_SUCCESS = '@@nsdb/HISTORICAL_QUERY_FETCH_SUCCESS';
const HISTORICAL_QUERY_FETCH_ERROR = '@@nsdb/HISTORICAL_QUERY_FETCH_ERROR';

const REALTIME_QUERY_START_SOCKET = '@@nsdb/REALTIME_QUERY_START_SOCKET';
const REALTIME_QUERY_STOP_SOCKET = '@@nsdb/REALTIME_QUERY_STOP_SOCKET';
const REALTIME_QUERY_ON_MESSAGE = '@@nsdb/REALTIME_QUERY_ON_MESSAGE';
const REALTIME_QUERY_ON_ERROR = '@@nsdb/REALTIME_QUERY_ON_ERROR';

export const types = {
  RESULT_REMOVE,
  HISTORICAL_QUERY_FETCH_REQUEST,
  HISTORICAL_QUERY_FETCH_SUCCESS,
  HISTORICAL_QUERY_FETCH_ERROR,
  REALTIME_QUERY_START_SOCKET,
  REALTIME_QUERY_STOP_SOCKET,
  REALTIME_QUERY_ON_MESSAGE,
  REALTIME_QUERY_ON_ERROR,
};
