#
#   Copyright 2018-2020 Radicalbit S.r.l.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#  
name: Continous Integration
on:
  pull_request:
    branches: [ 'master', 'branch-*' ]
  push:
    branches: [ 'master', 'branch-*' ]
    tags: [ '*' ]
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "openjdk@1.11"
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Code Style Check
        run: sbt fixCheck scalafmtCheck test:scalafmtCheck multi-jvm:scalafmtCheck
  cross-scala-compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "openjdk@1.11"
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Cross Compilation
        run: sbt +compile
  test:
    runs-on: ubuntu-latest
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "openjdk@1.11"
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Build and Test
        run: sbt -v coverage testAll
      - name: Coverage Report
        run: sbt coverageReport
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
  publish-test:
    needs:
      - code-style
      - cross-scala-compilation
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "openjdk@1.11"
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Test Publish Artifacts
        run: sbt +publishLocal
      - name: Test Publish Docker image
        run: sbt ";project nsdb-cluster; docker:publishLocal"
  publish-artifactory:
    if: github.event_name == 'push'
    needs:
      - publish-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "openjdk@1.11"
      - name: Create Credentials
        run: ./artifactory-credentials.sh ${{ secrets.ARTIFACTORTY_USERNAME }} ${{ secrets.ARTIFACTORTY_PASSWORD }}
      - name: Publish Artifacts
        run: sbt +publish
  publish-docker:
    if: github.event_name == 'push'
    needs:
      - publish-test
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "openjdk@1.11"
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - name: Publish Docker image
        run: sbt ";project nsdb-cluster; docker:publish"