name: Deploy
on:
  push:
    branches:
      - main
      - bramch-*
    tags:
      - *
jobs:
  publish-artifactory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Create Credentials
        run: ./artifactory-credentials.sh ${{ secrets.ARTIFACTORTY_USERNAME }} ${{ secrets.ARTIFACTORTY_PASSWORD }}
      - name: Publish Artifacts
        run: sbt +publish
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.8"
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: Publish Docker image
        run: sbt ";project nsdb-cluster; docker:publish"
